---
Context:
  type: VRE config
  id: 123e4567-e89b-12d3-a456-426655440000
Data:
  {% for dataset in datasets %}
  - id: {{dataset.id}}
    title: {{dataset.title}}
    resource: {{dataset.resource}}
    type: {{dataset.type}}
  {% endfor %}

Software:
    resource: https://...
    type: Jupyter
    dependencies:            
      {% for nb in notebooks %}
      - resource: {{nb.resource}}
        type: {{nb.type}}
        dependencies: {{nb.dependencies}}
      {% endfor %}
Environment:
  provider: PTEP
  processor: JupyterHub
