version: '3.3'

services:
  fastapi:
    # image: epinux/pybasket_api:latest
    image: epinux/fastapi:dev
    build:
      context: ./docker/fastapi
    environment:
        DOWNLOAD_DIR: "/app/download"
        DEBUG: 1
        PYTHONUNBUFFERED: 1
        LOGLEVEL: DEBUG
        RABBIT_HOST: "pyamqp://guest@rabbit//"
        API_HOST: "metsis.metsis-api.met.no"
        UI_HOST: "bokeh.metsis-api.met.no"
        PLOT_ENDPOINT: "https://bokeh.metsis-api.met.no/TS-Plot"
        WMS_ENDPOINT: "https://bokeh.metsis-api.met.no/GISPY"
        FORWARDED_ALLOW_IPS: "*"
        REDIS_HOST: "redis"
        FORWARDED_ALLOW_IPS: "*"
        REDIS_PASSWORD: 'FGX0Im8cROKpFpHPOP8FETmOpLPsiLwEnHHXprOgn2AR7r7cGp'
    volumes:
      - ./apps/pybasket_api:/app
    ports:
      - 8000:80
    hostname: fastapi
    depends_on: 
      - rabbit
      - worker
      - redis
      - bokeh
    links:
      - bokeh
    networks:
      - net
      - traefik-public
    deploy:
      resources:
        #limits:
        #  cpus: '0.50'
        #  memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.metsis-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.metsis-http.entrypoints=http
        - traefik.http.routers.metsis-http.middlewares=https-redirect
        - traefik.http.routers.metsis-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.metsis-https.entrypoints=https
        - traefik.http.routers.metsis-https.tls=true
        - traefik.http.routers.metsis-https.tls.certresolver=le
        - traefik.http.services.metsis.loadbalancer.server.port=80
        # allow CORS
        - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
        - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*"
        - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.testheader.headers.addvaryheader=true"

  rabbit:
    image: epinux/rabbitmq:local
    ports:
      - 5672:5672
    hostname: rabbit
    networks:
      - net 
  
  worker:
    # image: epinux/pybasket_api:latest
    image: epinux/fastapi:dev
    environment: 
      DOWNLOAD_DIR: "/app/download"
      PYTHONPATH: "/app"
      RABBIT_HOST: "pyamqp://guest@rabbit//"
      API_HOST: "metsis.metsis-api.met.no"
      UI_HOST: "bokeh.metsis-api.met.no"
      PLOT_ENDPOINT: "https://bokeh.metsis-api.met.no/TS-Plot"
      WMS_ENDPOINT: "https://bokeh.metsis-api.met.no/GISPY"
      REDIS_HOST: "redis"
      REDIS_PASSWORD: 'FGX0Im8cROKpFpHPOP8FETmOpLPsiLwEnHHXprOgn2AR7r7cGp'
      PYTHONUNBUFFERED: 1
    volumes:
      - ./apps/pybasket_api:/app
    entrypoint: celery --app=worker.celery_app worker -c 2 --loglevel=debug
    depends_on: 
      - rabbit
      - redis
    hostname: worker
    networks:
      - net  

  flower:  
    image: epinux/flower:local
    command: ["flower", "--broker=amqp://guest@rabbit//", "--port=8888"]  
    ports:  
      - 10000:8888 
    depends_on: 
      - rabbit
    hostname: flower
    networks:
      - net
      - traefik-public

  bokeh:
    # image: epinux/pybasket_ui:latest
    image: epinux/bokeh:dev
    build:
      context: ./docker/bokeh
    environment:
      BOKEH_ALLOW_WS_ORIGIN: 'metsis-staging.met.no,applicate.met.no,gcw.met.no,saon.met.no,yopp.met.no,nordatanet.no,gcw.met.no,metsis3.met.no,metsis4.met.no,metsis5.met.no,bokeh.metsis-api.met.no,metsis.metsis-api.met.no,metsis-dev.local,demosearch.metsis.met.no,nbs-staging.met.no,cvl.eo.esa.int,adc.met.no,satellittdata.no,www.satellittdata.no,satellittdata.com,www.satellittdata.com,sios-svalbard.org,www.sios-svalbard.org,157.249.72.82,157.249.75.175,157.249.73.143'
      PORT: '7000'
      LOG_LEVEL: 'debug'
      BOKEH_LOG_LEVEL: 'debug'
      API_HOST: "metsis.metsis-api.met.no"
      UI_HOST: "bokeh.metsis-api.met.no"
      PLOT_ENDPOINT: "https://bokeh.metsis-api.met.no/TS-Plot"
      WMS_ENDPOINT: "https://bokeh.metsis-api.met.no/GISPY"
      TSPLOT_DOWNLOAD: "/TS-Plot/static/Download"
      REDIS_HOST: "redis"
      REDIS_PASSWORD: 'FGX0Im8cROKpFpHPOP8FETmOpLPsiLwEnHHXprOgn2AR7r7cGp'
      PYTHONUNBUFFERED: 1
    volumes:
      - ./apps/pybasket_ui/dashboard:/pybasket_ui
      - ./apps/pybasket_ui/SIE:/SIE
      - ./apps/pybasket_ui/TS-Plot:/TS-Plot
      - ./apps/pybasket_ui/GISPY/gispy:/GISPY
      - ./apps/pybasket_ui/sea-ice-index-viz/bokeh-app:/SeaIce
      - ./apps/pybasket_ui/entrypoint.sh:/entrypoint.sh
    ports:
      - 7000:7000
    hostname: bokeh
    networks:
      - net
      - traefik-public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        # max_attempts: 5
        # window: 240s
      resources:
        #limits:
        #  cpus: '0.50'
        #  memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.bokeh-http.rule=Host(`${DOMAIN2?Variable not set}`)
        - traefik.http.routers.bokeh-http.entrypoints=http
        - traefik.http.routers.bokeh-http.middlewares=https-redirect
        - traefik.http.routers.bokeh-https.rule=Host(`${DOMAIN2?Variable not set}`)
        - traefik.http.routers.bokeh-https.entrypoints=https
        - traefik.http.routers.bokeh-https.tls=true
        - traefik.http.routers.bokeh-https.tls.certresolver=le
        - traefik.http.services.bokeh.loadbalancer.server.port=7000
        # allow CORS
        - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
        - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*"
        - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.testheader.headers.addvaryheader=true"

  redis:
    image: epinux/redis:local
    ports:
      - 6379:6379
    volumes:
      - ./apps/redis/data:/data
      - ./apps/redis/redis-base.conf:/usr/local/etc/redis/redis.conf
    command: '/usr/local/etc/redis/redis.conf --appendonly yes'
    hostname: redis
    networks:
      - net 

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

