FROM epinux/fastapi

LABEL maintainer="massimods@met.no"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y software-properties-common curl && curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update && apt-get install -y --no-install-recommends nodejs 

RUN apt-get install -y libproj-dev libgeos-dev proj-bin proj-data

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
COPY requirements.txt .
RUN pip install -U pip
RUN pip install -r requirements.txt

# RUN pip install ipyleaflet
RUN pip install owslib
RUN pip install geolinks
RUN pip install ipydatetime
# RUN pip install git+https://github.com/bokeh/ipywidgets_bokeh
RUN pip install shapely
RUN pip install colorcet


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 7000

ENV ORIGIN="0.0.0.0:7000" PORT="7000" PREFIX="" LOG_LEVEL="debug"

COPY ./app /app
ENTRYPOINT ["./entrypoint.sh"]


